//
// Created by roberto on 31/07/15.
//

#ifndef DNASEQUENCEGENERATOR_CONSTANTS_H
#define DNASEQUENCEGENERATOR_CONSTANTS_H

#define MATCH 1
#define MISMATCH -1
#define GAP -2

#endif //DNASEQUENCEGENERATOR_CONSTANTS_H
